SEQUOIADBMAINSTREAM-7990 升级工具需指定必填参数

diff --git a/tools/upgrade/sdbupgradeidx b/tools/upgrade/sdbupgradeidx
--- a/tools/upgrade/sdbupgradeidx
+++ b/tools/upgrade/sdbupgradeidx
@@ -40,10 +40,10 @@ function build_help()
    echo "sdbupgradeidx is a utility to upgrade index."
    echo ""
    echo "Common options:"
-   echo "  -s [ --hostname ] arg        host name, default: localhost"
-   echo "  -p [ --svcname ] arg         service name, default: 11810"
-   echo "  -o [ --output ] arg          specify the output file"
-   echo "  --action arg                 check or upgrade, defalut: check"
+   echo "  -s [ --hostname ] arg        host name"
+   echo "  -p [ --svcname ] arg         service name"
+   echo "  -o [ --output ] arg          specify the output file, default: ./sdbupgradeidx.log"
+   echo "  --action arg                 check or upgrade"
    echo "  -h [ --help ]                print help message"
    echo "  --version                    print version information"
    echo ""
@@ -63,13 +63,15 @@ GIT_VERSION="xxxxxxxxxx"
 BUILD_TIME="0000-00-00-00.00.00"
 
 # Default value
-HOSTNAME="localhost"
-SVCNAME=11810
+HAS_HOSTNAME=false
+HAS_SVCNAME=false
+HAS_ACTION=false
+HOSTNAME=""
+SVCNAME=""
+ACTION=""
 OUTPUT="./sdbupgradeidx.log"
-ACTION="check"
 
 # Parse command line parameters
-test $# -eq 0 && { build_help && exit 64; }
 
 ARGS=`getopt -o hs:p:o: --long help,version,hostname:,svcname:,output:,action: -n 'sdbupgradeidx' -- "$@"`
 ret=$?
@@ -81,14 +83,17 @@ while true
 do
    case "$1" in
       --action )          ACTION="$2"
+                          HAS_ACTION=true
                           test "$ACTION" == "check" -o "$ACTION" == "upgrade" \
                              || err_para ACTION "$ACTION"
                           shift 2
                           ;;
       -s | --hostname )   HOSTNAME=$2
+                          HAS_HOSTNAME=true
                           shift 2
                           ;;
       -p | --svcname )    SVCNAME=$2
+                          HAS_SVCNAME=true
                           check_num_para "SVCNAME" "$SVCNAME"
                           shift 2
                           ;;
@@ -109,6 +114,22 @@ do
                           ;;
    esac
 done
+
+if [ $HAS_HOSTNAME != true ]; then
+   echo "sdbupgradeidx: missing argument: hostname" >&2
+   echo 'Try "sdbupgradeidx --help" for more information.'
+   exit 64
+fi
+if [ $HAS_SVCNAME != true ]; then
+   echo "sdbupgradeidx: missing argument: svcname" >&2
+   echo 'Try "sdbupgradeidx --help" for more information.'
+   exit 64
+fi
+if [ $HAS_ACTION != true ]; then
+   echo "sdbupgradeidx: missing argument: action" >&2
+   echo 'Try "sdbupgradeidx --help" for more information.'
+   exit 64
+fi
 
 if [ "$*" != "" ]; then
    echo "sdbupgradeidx: too many arguments: $*" >&2
